apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
    - path: parent/
      repoURL: https://github.com/kahmnkk/sample-argo.git
      targetRevision: main
      helm:
        releaseName: parent-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: "argoproj.io/v1alpha1"
      jqPathExpressions:
        - .spec.sources[0].helm.parameters
      kind: Application
