apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
    - path: child/
      repoURL: https://github.com/kahmnkk/sample-argo.git
      targetRevision: main
      helm:
        releaseName: child-app
        parameters:
          - name: image.tag
            value: "latest"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: "*"
      jqPathExpressions:
        - .spec.template.spec.containers[0].ports
      kind: Deployment
