apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child
spec:
  sources:
    - path: child/
      repoURL: https://github.com/kahmnkk/sample-argo.git
      targetRevision: main
      helm:
        releaseName: child-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - .spec.destination
        - .spec.sources[0].helm.parameters
      kind: Application
